package com.beaconfire.quizsystem.entity.mentity;

public class Choice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.choice_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer choiceId;

    /**
     * 0 meaning not selected
     * 1 meaning selected
     * */
    private byte isSelected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.option_content
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private String optionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.is_correct
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Byte isCorrect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.choice_id
     *
     * @return the value of choice.choice_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getChoiceId() {
        return choiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.choice_id
     *
     * @param choiceId the value for choice.choice_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setChoiceId(Integer choiceId) {
        this.choiceId = choiceId;
    }


    public byte getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(byte isSelected) {
        this.isSelected = isSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.question_id
     *
     * @return the value of choice.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.question_id
     *
     * @param questionId the value for choice.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.option_content
     *
     * @return the value of choice.option_content
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public String getOptionContent() {
        return optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.option_content
     *
     * @param optionContent the value for choice.option_content
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setOptionContent(String optionContent) {
        this.optionContent = optionContent == null ? null : optionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.is_correct
     *
     * @return the value of choice.is_correct
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Byte getIsCorrect() {
        return isCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.is_correct
     *
     * @param isCorrect the value for choice.is_correct
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setIsCorrect(Byte isCorrect) {
        this.isCorrect = isCorrect;
    }
}