package com.beaconfire.quizsystem.entity.mentity;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedback_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.user_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer quizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.rating
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.review
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private String review;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedback_id
     *
     * @return the value of feedback.feedback_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.feedback_id
     *
     * @param feedbackId the value for feedback.feedback_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.user_id
     *
     * @return the value of feedback.user_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.user_id
     *
     * @param userId the value for feedback.user_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.quiz_id
     *
     * @return the value of feedback.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.quiz_id
     *
     * @param quizId the value for feedback.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.rating
     *
     * @return the value of feedback.rating
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.rating
     *
     * @param rating the value for feedback.rating
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.review
     *
     * @return the value of feedback.review
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public String getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.review
     *
     * @param review the value for feedback.review
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setReview(String review) {
        this.review = review == null ? null : review.trim();
    }
}