package com.beaconfire.quizsystem.entity.mentity;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer quizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_content
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_status
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private String questionStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_id
     *
     * @return the value of question.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_id
     *
     * @param questionId the value for question.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.quiz_id
     *
     * @return the value of question.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.quiz_id
     *
     * @param quizId the value for question.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_content
     *
     * @return the value of question.question_content
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_content
     *
     * @param questionContent the value for question.question_content
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent == null ? null : questionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_status
     *
     * @return the value of question.question_status
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public String getQuestionStatus() {
        return questionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_status
     *
     * @param questionStatus the value for question.question_status
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuestionStatus(String questionStatus) {
        this.questionStatus = questionStatus == null ? null : questionStatus.trim();
    }
}