package com.beaconfire.quizsystem.entity.mentity;

public class QuizResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_result.quiz_result_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer quizResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_result.take_quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer takeQuizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_result.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_result.user_choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private String userChoice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_result.quiz_result_id
     *
     * @return the value of quiz_result.quiz_result_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuizResultId() {
        return quizResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_result.quiz_result_id
     *
     * @param quizResultId the value for quiz_result.quiz_result_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuizResultId(Integer quizResultId) {
        this.quizResultId = quizResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_result.take_quiz_id
     *
     * @return the value of quiz_result.take_quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getTakeQuizId() {
        return takeQuizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_result.take_quiz_id
     *
     * @param takeQuizId the value for quiz_result.take_quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setTakeQuizId(Integer takeQuizId) {
        this.takeQuizId = takeQuizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_result.question_id
     *
     * @return the value of quiz_result.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_result.question_id
     *
     * @param questionId the value for quiz_result.question_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_result.user_choice
     *
     * @return the value of quiz_result.user_choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public String getUserChoice() {
        return userChoice;
    }

    public void setUserChoice(String userChoice) {
        this.userChoice = userChoice;
    }
}