package com.beaconfire.quizsystem.entity.mentity;

import java.util.Date;

public class TakeQuiz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take_quiz.take_quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer takeQuizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take_quiz.user_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take_quiz.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer quizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take_quiz.start_time
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Long startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take_quiz.finish_time
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Long finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take_quiz.score
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take_quiz.take_quiz_id
     *
     * @return the value of take_quiz.take_quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getTakeQuizId() {
        return takeQuizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take_quiz.take_quiz_id
     *
     * @param takeQuizId the value for take_quiz.take_quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setTakeQuizId(Integer takeQuizId) {
        this.takeQuizId = takeQuizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take_quiz.user_id
     *
     * @return the value of take_quiz.user_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take_quiz.user_id
     *
     * @param userId the value for take_quiz.user_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take_quiz.quiz_id
     *
     * @return the value of take_quiz.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take_quiz.quiz_id
     *
     * @param quizId the value for take_quiz.quiz_id
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take_quiz.start_time
     *
     * @return the value of take_quiz.start_time
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take_quiz.start_time
     *
     * @param startTime the value for take_quiz.start_time
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take_quiz.finish_time
     *
     * @return the value of take_quiz.finish_time
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Long getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take_quiz.finish_time
     *
     * @param finishTime the value for take_quiz.finish_time
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setFinishTime(Long finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take_quiz.score
     *
     * @return the value of take_quiz.score
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take_quiz.score
     *
     * @param score the value for take_quiz.score
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}