package com.beaconfire.quizsystem.dao;


import com.beaconfire.quizsystem.entity.mentity.Choice;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int deleteByPrimaryKey(Integer choiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insert(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insertSelective(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    Choice selectByPrimaryKey(Integer choiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKeySelective(Choice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKey(Choice record);

    List<Choice> selectByQuestionId(int questionId);
}