package com.beaconfire.quizsystem.dao;


import com.beaconfire.quizsystem.entity.mentity.Feedback;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int deleteByPrimaryKey(Integer feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    Feedback selectByPrimaryKey(Integer feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKey(Feedback record);
}