package com.beaconfire.quizsystem.dao;


import com.beaconfire.quizsystem.entity.mentity.Quiz;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface QuizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int deleteByPrimaryKey(Integer quizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insert(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insertSelective(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    Quiz selectByPrimaryKey(Integer quizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKeySelective(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKey(Quiz record);

    List<Quiz> selectAll();
}