package com.beaconfire.quizsystem.dao;


import com.beaconfire.quizsystem.entity.mentity.TakeQuiz;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TakeQuizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take_quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int deleteByPrimaryKey(Integer takeQuizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take_quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insert(TakeQuiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take_quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insertSelective(TakeQuiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take_quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    TakeQuiz selectByPrimaryKey(Integer takeQuizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take_quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKeySelective(TakeQuiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take_quiz
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int updateByPrimaryKey(TakeQuiz record);
}