package com.beaconfire.quizsystem.dao;

import com.beaconfire.quizsystem.entity.mentity.User;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Aug 12 18:04:00 EDT 2022
     */
    int insertSelective(User record);

    User selectByUsername(String username);

    User selectByPrimaryKey(Integer id);
}